### PR TITLE
Provide support for Cobbler 3.2.x 

### PR DESCRIPTION
**Pull request by hbokh**
This PR provides support for Cobbler 3, specifically **Cobbler 3.2.0** and higher.
The code in this fork is in use by _Devhouse Spindle_ since spring 2020 with a slightly adapted version of Cobbler to disable heavy caching.

For Cobbler 3.2.0, @holmesb adapted the code to make the caching in Cobbler  a setting.

This should be added specifically:
In Cobbler 3.2.0, add: `cache_enabled: 0` to `/etc/cobbler/settings` (default is 1).

### CODE REVIEW

**Comment by hbokh** [comment]
@holmesb @jtopjian Does anyone of you know someone (for example at Hashicorp) we can poke to get this moving?

**Comment by jtopjian** [comment]
@hbokh Unfortunately no. I tried contacting someone a few months ago and never got a response.

I think Hashicorp has changed the structure of their "official" providers, reducing it only to a handful. The other providers taken over by individual maintainers outside of Hashicorp. For example, https://github.com/terraform-providers/terraform-provider-openstack is now https://github.com/terraform-provider-openstack/terraform-provider-openstack.

In the past, I suggested avoiding a fork of this provider and to try to get things officially merged. Unless someone jumps in to correct me, forking and taking over is the only option at this point. 😞

**Comment by holmesb** [comment]
Prob worth checking with the [owners ](https://github.com/orgs/terraform-providers/people) of the terraform-providers github project whether they would like the broken provider on [their site ](https://www.terraform.io/docs/providers/cobbler/index.html) fixed.  If not, I guess we create a fork: https://github.com/terraform-provider-cobbler and publish in the [registry](https://registry.terraform.io/browse/providers).

**Comment by hbokh** [comment]
> Prob worth checking with the [owners ](https://github.com/orgs/terraform-providers/people) of the terraform-providers github project whether they would like the broken provider on [their site ](https://www.terraform.io/docs/providers/cobbler/index.html) fixed. If not, I guess we create a fork: https://github.com/terraform-provider-cobbler and publish in the [registry](https://registry.terraform.io/browse/providers).

Ping @aareet / @austingebauer / @kmoe / @manicminer / @radeksimko 

Sorry for the "mass mailing", but can any of you shine a light on this, please? TIA!

**Comment by aicarmic** [comment]
Thanks for the note @hbokh. We're in the process of migrating providers out of the `terraform-providers` namespace since 0.13 introduced provider source and self-service publishing to the [Terraform Registry](http://registry.terraform.io/). Forking is the easiest path forward for community-maintained providers. If the original maintainer is interested, we can transfer over all open issues and PRs, and mention the new location prior to archiving. Once published, we will also point documentation to the Registry as well for a smooth transition. Let us know how we can help!

**Comment by jtopjian** [comment]
@aicarmic I was previously the maintainer of this provider but stepped down a while back. I don't know if there has been another officially designated maintainer since then. If there hasn't and if anyone in this thread is willing to take ownership, that would be awesome.

**Comment by aicarmic** [comment]
@jtopjian it looks like @hbokh is going ahead with a fork and prepping that for publish. If you'd like, we can mark the original in `terraform-providers` as archived, and point to the new one once it is published. Does that work for both of you?

**Comment by jtopjian** [comment]
Sounds good to me - thank you!

**Comment by hbokh** [comment]
> @jtopjian it looks like @hbokh is going ahead with a fork and prepping that for publish. If you'd like, we can mark the original in `terraform-providers` as archived, and point to the new one once it is published. Does that work for both of you?

I have no knowledge (yet) on how to prepare things for publish... Is there something I can read up on to get into this, @aicarmic ?

Also, the two repositories have been transferred  from _github.com/wearespindle_ (my employer) to the cobbler org.

**Comment by jtopjian** [comment]
> I have no knowledge (yet) on how to prepare things for publish

This doc provides all the information needed. I followed it for a provider of mine and found it pretty straightforward.

https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by aicarmic** [comment]
@hbokh I should add that our team is working on a tool to generate documentation. We haven't formally announced it yet, but if you'd like to give it a try you can find it here: https://github.com/hashicorp/terraform-plugin-docs

It requires you to define Description values in your schema information. @paultyng used it to generate the docs currently on the [UniFi provider](https://registry.terraform.io/providers/paultyng/unifi/latest/docs/resources/wlan)

**Comment by hbokh** [comment]
Closed. I am nearing the point of publishing a community plugin under the Cobbler organisation.
Thanks for the help, folks! 🙌🏼

**Pull request closed without merging**
