### PR TITLE
Update to support v0.12.0

### PR DESCRIPTION
**Pull request by hbokh**
This will solve #24. CC @radeksimko & @jtopjian.

I managed to get a new binary in `$GOPATH/bin/terraform-provider-cobbler` using the steps described in [Upgrading to the latest Terraform SDK](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#upgrading-to-the-latest-terraform-sdk).
Version used was `github.com/hashicorp/terraform@v0.12.0`, not yet v0.12.1...

Testing -in a **very hacky way**- was done by copying that same binary over `~/Projects/terraform2cobbler/.terraform/plugins/darwin_amd64/terraform-provider-cobbler_v1.0.1_x4`; removing the file `lock.json` inthere and run `~/bin/terraform-0.12.0 init`.

I deleted a pre-used test system in Cobbler itself and ran `~/bin/terraform-0.12.0 plan` plus `~/bin/terraform-0.12.0 apply` on an existing system definition in `main.tf` and the system was added to Cobbler without issue.

To me this seems like a working upgrade, but YMMV.
For instance, I'm not sure how to bump the version that is on v1.0.1 in this branch.
Where & how do I set it (in what file) and what number would fit this release? Something like v1.0.2 or maybe even v1.2.0?

### Version

```
~/bin/terraform-0.12.0 --version 
Terraform v0.12.0
+ provider.cobbler v1.0.1

Your version of Terraform is out of date! The latest version
is 0.12.1. You can update by downloading from www.terraform.io/downloads.html
```

### CODE REVIEW

**Comment by hbokh** [comment]
😢

Don't know...
`make test`; `make vet` & `make website-test` all run OK on my Mac.
Running on `go version go1.12.5 darwin/amd64`.

**Comment by jtopjian** [comment]
Can you try the following on a clean branch?

```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
go mod vendor
```

Let me know if that gives you any problems and I'll see if I can figure out where the issue is coming from.

**Comment by jtopjian** [comment]
Also,

> For instance, I'm not sure how to bump the version that is on v1.0.1 in this branch.
> Where & how do I set it (in what file) and what number would fit this release? Something like v1.0.2 or maybe even v1.2.0?

This is all done by HashiCorp when a new release is made. 

~If you test with a binary built from source, the `-version` should reflect that.~ Sorry, that doesn't work for plugins.

The actual name of the binary can either match the existing one (in order to overwrite your existing plugin file) or you can call the built one `terraform-provider-cobbler` and delete the existing one.

**Comment by hbokh** [comment]
Thanks for the response, Joe!

> Can you try the following on a clean branch?
> 
> ```
> go get github.com/hashicorp/terraform@v0.12.0
> go mod tidy
> go mod vendor
> ```
> 
> Let me know if that gives you any problems and I'll see if I can figure out where the issue is coming from.

Started from a fresh clone:
```
$ git clone git@github.com:hbokh/terraform-provider-cobbler.git
$ cd terraform-provider-cobbler
$ git checkout feature/support-terraform-v0.12.x
Branch 'feature/support-terraform-v0.12.x' set up to track remote branch 'feature/support-terraform-v0.12.x' from 'origin'.
Switched to a new branch 'feature/support-terraform-v0.12.x'

$ go get github.com/hashicorp/terraform@v0.12.0
go: downloading github.com/hashicorp/serf v0.0.0-20160124182025-e4ec8cc423bb
go: extracting github.com/hashicorp/serf v0.0.0-20160124182025-e4ec8cc423bb

$ go mod tidy
$ go mod vendor
```

No alarming messages here.

After that (again) `make test / vet / build` all work without error.
Binaries `terraform` and `terraform-provider-cobbler` can be found in `$GOPATH/bin`.

**Comment by jtopjian** [comment]
hm... I'm a little puzzled at where the Travis errors are coming. If I run the same 3 commands on a clean branch, things are passing for me:

https://travis-ci.org/terraform-providers/terraform-provider-cobbler/builds/541944248

**Comment by jtopjian** [comment]
@hbokh _something_ is different between our two PRs (#26). In mine, I have 1,427 changed files instead of 681 with this PR.

I'm happy to help debug what the difference is, unless you'd like to just defer to #26?

**Comment by hbokh** [comment]
> @hbokh _something_ is different between our two PRs (#26). In mine, I have 1,427 changed files instead of 681 with this PR.
> 
> I'm happy to help debug what the difference is, unless you'd like to just defer to #26?

The goal is to get a new provider for Cobbler. You managed to get that done (I almost got there). 😇
Since I'm not that good with Go and debugging will take me some more time, I'm happy to close this PR and you push #26.
Thanks for your time, Joe!

**Pull request closed without merging**
