### PR TITLE
vendor: Updating to Terraform v0.12

### PR DESCRIPTION
**Pull request by jtopjian**

### CODE REVIEW

**Comment by jtopjian** [comment]
```
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccCobblerDistro_basic
--- PASS: TestAccCobblerDistro_basic (0.93s)
=== RUN   TestAccCobblerDistro_change
--- PASS: TestAccCobblerDistro_change (0.94s)
=== RUN   TestAccCobblerKickstartFile_basic
--- PASS: TestAccCobblerKickstartFile_basic (0.12s)
=== RUN   TestAccCobblerProfile_basic
--- PASS: TestAccCobblerProfile_basic (1.28s)
=== RUN   TestAccCobblerProfile_change
--- PASS: TestAccCobblerProfile_change (1.51s)
=== RUN   TestAccCobblerProfile_withRepo
--- PASS: TestAccCobblerProfile_withRepo (1.26s)
=== RUN   TestAccCobblerRepo_basic
--- PASS: TestAccCobblerRepo_basic (0.13s)
=== RUN   TestAccCobblerRepo_change
--- PASS: TestAccCobblerRepo_change (0.22s)
=== RUN   TestAccCobblerSnippet_basic
--- PASS: TestAccCobblerSnippet_basic (0.07s)
=== RUN   TestAccCobblerSystem_basic
--- PASS: TestAccCobblerSystem_basic (5.45s)
=== RUN   TestAccCobblerSystem_multi
--- PASS: TestAccCobblerSystem_multi (191.56s)
=== RUN   TestAccCobblerSystem_change
--- PASS: TestAccCobblerSystem_change (8.08s)
=== RUN   TestAccCobblerSystem_removeInterface
--- PASS: TestAccCobblerSystem_removeInterface (8.08s)
PASS
ok      github.com/terraform-providers/terraform-provider-cobbler/cobbler       219.678s
```

**Comment by hbokh** [comment]
LGTM 😄

**Comment by hbokh** [comment]
So, who needs to / can approve this PR? @radeksimko ?
I'd be very happy if I could start using the new provider after this years Pentecost. 😇

But maybe also adapt this for the v0.12.1 release of Terraform.

**Review by radeksimko — APPROVED** [review]
LGTM. I also ran acceptance tests in TeamCity and these were green on your branch. 👍 

:shipit:

**Pull request merged**
